# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=100)),
                ('number_of_building', models.CharField(max_length=10)),
                ('number_of_flat', models.CharField(max_length=10)),
                ('available_from', models.DateField(verbose_name='available from')),
                ('available_to', models.DateField(verbose_name='available to')),
                ('status', models.BooleanField(default=True)),
                ('nickname', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.City')),
            ],
        ),
    ]
