# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='rented_from',
            field=models.DateField(blank=True, null=True, verbose_name='rented from'),
        ),
        migrations.AddField(
            model_name='flat',
            name='rented_to',
            field=models.DateField(blank=True, null=True, verbose_name='rented to'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='nickname',
            field=models.CharField(default='nobody', max_length=100),
        ),
    ]
