# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20170125_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('n', 'not available')], max_length=1),
        ),
    ]
